export const TIMING = {
  cubeStart: 0,
  cubeEnd: 30,
  enStart: 30,
  enMainRevealStart: 36,
  enMainRevealEnd: 56,
  enReflectionRevealStart: 44,
  enReflectionRevealEnd: 64,
  splitFadeStart: 56,
  splitFadeEnd: 68,
  enEnd: 75,
  copyStart: 75,
  copyLineDrawStart: 75,
  copyLineDrawEnd: 81,
  copyRevealStart: 80,
  copyRevealEnd: 92,
  copyLineFadeStart: 91,
  copyLineFadeEnd: 99,
  copyEnd: 99,
  wordmarkStart: 99,
  wordmarkEnd: 114,
  taglineStart: 105,
  taglineEnd: 120,
  finalHoldStart: 120,
  duration: 150,
} as const;
